In [1]:
import torch

In [2]:
x = torch.empty(5,3)

In [3]:
x

tensor([[8.4490e-39, 9.6429e-39, 9.2755e-39],
        [1.0286e-38, 9.0919e-39, 8.9082e-39],
        [9.2755e-39, 8.4490e-39, 1.0194e-38],
        [9.0919e-39, 8.4490e-39, 1.0653e-38],
        [9.9184e-39, 8.4490e-39, 8.9082e-39]])

随机初始化一个tensor

In [4]:
torch.rand(5,3)

tensor([[0.4508, 0.7695, 0.8392],
        [0.9745, 0.2436, 0.2036],
        [0.8718, 0.6173, 0.4580],
        [0.3774, 0.4038, 0.6263],
        [0.9276, 0.8007, 0.8156]])

In [5]:
torch.zeros(5, 3, dtype=torch.long)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])

In [6]:
torch.tensor([5.3, 3])

tensor([5.3000, 3.0000])

In [7]:
x = x.new_ones(5,3)

In [8]:
x

tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])

In [9]:
x = torch.randn_like(x)

In [10]:
x

tensor([[-0.2343,  0.0843, -0.3211],
        [-2.6052,  1.0966,  0.6667],
        [-0.7716,  0.2564, -0.1489],
        [-0.6013, -1.3153, -0.2028],
        [-1.1788, -1.0547, -1.4170]])

In [11]:
x.size()
x.shape

torch.Size([5, 3])

In [12]:
torch.normal(mean=0, std=1, size=[5,3])

tensor([[ 1.9391,  0.7875, -0.1159],
        [-0.9598,  1.0120, -0.6132],
        [ 0.3331,  0.3929, -0.5875],
        [ 2.9932, -1.3252, -0.3550],
        [-0.0097,  1.5945, -0.1249]])

In [16]:
x = torch.ones(2,2)

In [17]:
x

tensor([[1., 1.],
        [1., 1.]])

In [18]:
y = torch.zeros(2,2)
y

tensor([[0., 0.],
        [0., 0.]])

In [19]:
x+y

tensor([[1., 1.],
        [1., 1.]])

In [20]:
z = torch.add(x, y)
z

tensor([[1., 1.],
        [1., 1.]])

In [21]:
torch.add(x, y, out=a)

NameError: name 'a' is not defined

In [22]:
a = torch.randn(2,2)
torch.add(x, y, out=a)

tensor([[1., 1.],
        [1., 1.]])

In [23]:
a

tensor([[1., 1.],
        [1., 1.]])

In [25]:
a = torch.arange(24)

In [26]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [27]:
a.reshape(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [28]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [29]:
torch.reshape(a, (2,3,4))

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [30]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [31]:
b = a.reshape(2,3,4)
b

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [33]:
b.index_select(dim=1,index=2)

TypeError: index_select() received an invalid combination of arguments - got (dim=int, index=int, ), but expected one of:
 * (name dim, Tensor index)
      didn't match because some of the arguments have invalid types: (dim=int, index=int, )
 * (int dim, Tensor index)
      didn't match because some of the arguments have invalid types: (dim=int, index=int, )


In [34]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [35]:
a.view(2,3,4)

tensor([[[ 0,  1,  2,  3],
         [ 4,  5,  6,  7],
         [ 8,  9, 10, 11]],

        [[12, 13, 14, 15],
         [16, 17, 18, 19],
         [20, 21, 22, 23]]])

In [36]:
a

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
        18, 19, 20, 21, 22, 23])

In [37]:
torch.cuda.is_available()


True